spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task-manager
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect

jwt:
  secret.key: 687ab2112840758bc705ae65724e03a81738f9aea7bba136ed80453a0ca18ecb
  time.expiration: 86400000